//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using PsychologicalServices.Data;
using PsychologicalServices.Data.HelperClasses;
using PsychologicalServices.Data.FactoryClasses;
using PsychologicalServices.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PsychologicalServices.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'GoseInterview'.<br/><br/></summary>
	[Serializable]
	public partial class GoseInterviewEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		#region Class Member Declarations
		private AssessmentEntity _assessment;
		private GoseAccidentTimeframeEntity _goseAccidentTimeframe;
		private GoseFamilyAndFriendshipsDisruptionLevelEntity _goseFamilyAndFriendshipsDisruptionLevel;
		private GoseRespondentTypeEntity _goseRespondentType;
		private GoseReturnToNormalLifeOutcomeFactorEntity _goseReturnToNormalLifeOutcomeFactor;
		private GoseSocialAndLeisureRestrictionExtentEntity _goseSocialAndLeisureRestrictionExtent;
		private GoseWorkRestrictionLevelEntity _goseWorkRestrictionLevel;
		private UserEntity _createUser;
		private UserEntity _updateUser;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		#endregion

		#region Statics
		private static Dictionary<string, string>	_customProperties;
		private static Dictionary<string, Dictionary<string, string>>	_fieldsCustomProperties;

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Assessment</summary>
			public static readonly string Assessment = "Assessment";
			/// <summary>Member name GoseAccidentTimeframe</summary>
			public static readonly string GoseAccidentTimeframe = "GoseAccidentTimeframe";
			/// <summary>Member name GoseFamilyAndFriendshipsDisruptionLevel</summary>
			public static readonly string GoseFamilyAndFriendshipsDisruptionLevel = "GoseFamilyAndFriendshipsDisruptionLevel";
			/// <summary>Member name GoseRespondentType</summary>
			public static readonly string GoseRespondentType = "GoseRespondentType";
			/// <summary>Member name GoseReturnToNormalLifeOutcomeFactor</summary>
			public static readonly string GoseReturnToNormalLifeOutcomeFactor = "GoseReturnToNormalLifeOutcomeFactor";
			/// <summary>Member name GoseSocialAndLeisureRestrictionExtent</summary>
			public static readonly string GoseSocialAndLeisureRestrictionExtent = "GoseSocialAndLeisureRestrictionExtent";
			/// <summary>Member name GoseWorkRestrictionLevel</summary>
			public static readonly string GoseWorkRestrictionLevel = "GoseWorkRestrictionLevel";
			/// <summary>Member name CreateUser</summary>
			public static readonly string CreateUser = "CreateUser";
			/// <summary>Member name UpdateUser</summary>
			public static readonly string UpdateUser = "UpdateUser";
		}
		#endregion
		
		/// <summary> Static CTor for setting up custom property hashtables. Is executed before the first instance of this entity class or derived classes is constructed. </summary>
		static GoseInterviewEntity()
		{
			SetupCustomPropertyHashtables();
		}
		
		/// <summary> CTor</summary>
		public GoseInterviewEntity():base("GoseInterviewEntity")
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <remarks>For framework usage.</remarks>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public GoseInterviewEntity(IEntityFields2 fields):base("GoseInterviewEntity")
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this GoseInterviewEntity</param>
		public GoseInterviewEntity(IValidator validator):base("GoseInterviewEntity")
		{
			InitClassEmpty(validator, null);
		}
				
		/// <summary> CTor</summary>
		/// <param name="goseInterviewId">PK value for GoseInterview which data should be fetched into this GoseInterview object</param>
		/// <remarks>The entity is not fetched by this constructor. Use a DataAccessAdapter for that.</remarks>
		public GoseInterviewEntity(System.Int32 goseInterviewId):base("GoseInterviewEntity")
		{
			InitClassEmpty(null, null);
			this.GoseInterviewId = goseInterviewId;
		}

		/// <summary> CTor</summary>
		/// <param name="goseInterviewId">PK value for GoseInterview which data should be fetched into this GoseInterview object</param>
		/// <param name="validator">The custom validator object for this GoseInterviewEntity</param>
		/// <remarks>The entity is not fetched by this constructor. Use a DataAccessAdapter for that.</remarks>
		public GoseInterviewEntity(System.Int32 goseInterviewId, IValidator validator):base("GoseInterviewEntity")
		{
			InitClassEmpty(validator, null);
			this.GoseInterviewId = goseInterviewId;
		}

		/// <summary> Protected CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		[EditorBrowsable(EditorBrowsableState.Never)]
		protected GoseInterviewEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			if(SerializationHelper.Optimization != SerializationOptimization.Fast) 
			{
				_assessment = (AssessmentEntity)info.GetValue("_assessment", typeof(AssessmentEntity));
				if(_assessment!=null)
				{
					_assessment.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_goseAccidentTimeframe = (GoseAccidentTimeframeEntity)info.GetValue("_goseAccidentTimeframe", typeof(GoseAccidentTimeframeEntity));
				if(_goseAccidentTimeframe!=null)
				{
					_goseAccidentTimeframe.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_goseFamilyAndFriendshipsDisruptionLevel = (GoseFamilyAndFriendshipsDisruptionLevelEntity)info.GetValue("_goseFamilyAndFriendshipsDisruptionLevel", typeof(GoseFamilyAndFriendshipsDisruptionLevelEntity));
				if(_goseFamilyAndFriendshipsDisruptionLevel!=null)
				{
					_goseFamilyAndFriendshipsDisruptionLevel.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_goseRespondentType = (GoseRespondentTypeEntity)info.GetValue("_goseRespondentType", typeof(GoseRespondentTypeEntity));
				if(_goseRespondentType!=null)
				{
					_goseRespondentType.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_goseReturnToNormalLifeOutcomeFactor = (GoseReturnToNormalLifeOutcomeFactorEntity)info.GetValue("_goseReturnToNormalLifeOutcomeFactor", typeof(GoseReturnToNormalLifeOutcomeFactorEntity));
				if(_goseReturnToNormalLifeOutcomeFactor!=null)
				{
					_goseReturnToNormalLifeOutcomeFactor.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_goseSocialAndLeisureRestrictionExtent = (GoseSocialAndLeisureRestrictionExtentEntity)info.GetValue("_goseSocialAndLeisureRestrictionExtent", typeof(GoseSocialAndLeisureRestrictionExtentEntity));
				if(_goseSocialAndLeisureRestrictionExtent!=null)
				{
					_goseSocialAndLeisureRestrictionExtent.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_goseWorkRestrictionLevel = (GoseWorkRestrictionLevelEntity)info.GetValue("_goseWorkRestrictionLevel", typeof(GoseWorkRestrictionLevelEntity));
				if(_goseWorkRestrictionLevel!=null)
				{
					_goseWorkRestrictionLevel.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_createUser = (UserEntity)info.GetValue("_createUser", typeof(UserEntity));
				if(_createUser!=null)
				{
					_createUser.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_updateUser = (UserEntity)info.GetValue("_updateUser", typeof(UserEntity));
				if(_updateUser!=null)
				{
					_updateUser.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				this.FixupDeserialization(FieldInfoProviderSingleton.GetInstance());
			}
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		
		/// <summary>Performs the desync setup when an FK field has been changed. The entity referenced based on the FK field will be dereferenced and sync info will be removed.</summary>
		/// <param name="fieldIndex">The fieldindex.</param>
		protected override void PerformDesyncSetupFKFieldChange(int fieldIndex)
		{
			switch((GoseInterviewFieldIndex)fieldIndex)
			{
				case GoseInterviewFieldIndex.AssessmentId:
					DesetupSyncAssessment(true, false);
					break;
				case GoseInterviewFieldIndex.AccidentTimeframeId:
					DesetupSyncGoseAccidentTimeframe(true, false);
					break;
				case GoseInterviewFieldIndex.RespondentTypeId:
					DesetupSyncGoseRespondentType(true, false);
					break;
				case GoseInterviewFieldIndex.WorkRestrictionLevelId:
					DesetupSyncGoseWorkRestrictionLevel(true, false);
					break;
				case GoseInterviewFieldIndex.SocialAndLeisureExtentOfRestrictionId:
					DesetupSyncGoseSocialAndLeisureRestrictionExtent(true, false);
					break;
				case GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionLevelId:
					DesetupSyncGoseFamilyAndFriendshipsDisruptionLevel(true, false);
					break;
				case GoseInterviewFieldIndex.ReturnToNormalLifeMostImportantFactorInOutcomeId:
					DesetupSyncGoseReturnToNormalLifeOutcomeFactor(true, false);
					break;
				case GoseInterviewFieldIndex.CreateUserId:
					DesetupSyncCreateUser(true, false);
					break;
				case GoseInterviewFieldIndex.UpdateUserId:
					DesetupSyncUpdateUser(true, false);
					break;
				default:
					base.PerformDesyncSetupFKFieldChange(fieldIndex);
					break;
			}
		}

		/// <summary> Sets the related entity property to the entity specified. If the property is a collection, it will add the entity specified to that collection.</summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <param name="entity">Entity to set as an related entity</param>
		/// <remarks>Used by prefetch path logic.</remarks>
		protected override void SetRelatedEntityProperty(string propertyName, IEntityCore entity)
		{
			switch(propertyName)
			{
				case "Assessment":
					this.Assessment = (AssessmentEntity)entity;
					break;
				case "GoseAccidentTimeframe":
					this.GoseAccidentTimeframe = (GoseAccidentTimeframeEntity)entity;
					break;
				case "GoseFamilyAndFriendshipsDisruptionLevel":
					this.GoseFamilyAndFriendshipsDisruptionLevel = (GoseFamilyAndFriendshipsDisruptionLevelEntity)entity;
					break;
				case "GoseRespondentType":
					this.GoseRespondentType = (GoseRespondentTypeEntity)entity;
					break;
				case "GoseReturnToNormalLifeOutcomeFactor":
					this.GoseReturnToNormalLifeOutcomeFactor = (GoseReturnToNormalLifeOutcomeFactorEntity)entity;
					break;
				case "GoseSocialAndLeisureRestrictionExtent":
					this.GoseSocialAndLeisureRestrictionExtent = (GoseSocialAndLeisureRestrictionExtentEntity)entity;
					break;
				case "GoseWorkRestrictionLevel":
					this.GoseWorkRestrictionLevel = (GoseWorkRestrictionLevelEntity)entity;
					break;
				case "CreateUser":
					this.CreateUser = (UserEntity)entity;
					break;
				case "UpdateUser":
					this.UpdateUser = (UserEntity)entity;
					break;
				default:
					this.OnSetRelatedEntityProperty(propertyName, entity);
					break;
			}
		}
		
		/// <summary>Gets the relation objects which represent the relation the fieldName specified is mapped on. </summary>
		/// <param name="fieldName">Name of the field mapped onto the relation of which the relation objects have to be obtained.</param>
		/// <returns>RelationCollection with relation object(s) which represent the relation the field is maped on</returns>
		protected override RelationCollection GetRelationsForFieldOfType(string fieldName)
		{
			return GetRelationsForField(fieldName);
		}

		/// <summary>Gets the relation objects which represent the relation the fieldName specified is mapped on. </summary>
		/// <param name="fieldName">Name of the field mapped onto the relation of which the relation objects have to be obtained.</param>
		/// <returns>RelationCollection with relation object(s) which represent the relation the field is maped on</returns>
		internal static RelationCollection GetRelationsForField(string fieldName)
		{
			RelationCollection toReturn = new RelationCollection();
			switch(fieldName)
			{
				case "Assessment":
					toReturn.Add(Relations.AssessmentEntityUsingAssessmentId);
					break;
				case "GoseAccidentTimeframe":
					toReturn.Add(Relations.GoseAccidentTimeframeEntityUsingAccidentTimeframeId);
					break;
				case "GoseFamilyAndFriendshipsDisruptionLevel":
					toReturn.Add(Relations.GoseFamilyAndFriendshipsDisruptionLevelEntityUsingFamilyAndFriendshipsDisruptionLevelId);
					break;
				case "GoseRespondentType":
					toReturn.Add(Relations.GoseRespondentTypeEntityUsingRespondentTypeId);
					break;
				case "GoseReturnToNormalLifeOutcomeFactor":
					toReturn.Add(Relations.GoseReturnToNormalLifeOutcomeFactorEntityUsingReturnToNormalLifeMostImportantFactorInOutcomeId);
					break;
				case "GoseSocialAndLeisureRestrictionExtent":
					toReturn.Add(Relations.GoseSocialAndLeisureRestrictionExtentEntityUsingSocialAndLeisureExtentOfRestrictionId);
					break;
				case "GoseWorkRestrictionLevel":
					toReturn.Add(Relations.GoseWorkRestrictionLevelEntityUsingWorkRestrictionLevelId);
					break;
				case "CreateUser":
					toReturn.Add(Relations.UserEntityUsingCreateUserId);
					break;
				case "UpdateUser":
					toReturn.Add(Relations.UserEntityUsingUpdateUserId);
					break;
				default:
					break;				
			}
			return toReturn;
		}

		/// <summary>Checks if the relation mapped by the property with the name specified is a one way / single sided relation. If the passed in name is null, it/ will return true if the entity has any single-sided relation</summary>
		/// <param name="propertyName">Name of the property which is mapped onto the relation to check, or null to check if the entity has any relation/ which is single sided</param>
		/// <returns>true if the relation is single sided / one way (so the opposite relation isn't present), false otherwise</returns>
		protected override bool CheckOneWayRelations(string propertyName)
		{
			int numberOfOneWayRelations = 0;
			switch(propertyName)
			{
				case null:
					return ((numberOfOneWayRelations > 0) || base.CheckOneWayRelations(null));
				default:
					return base.CheckOneWayRelations(propertyName);
			}
		}

		/// <summary> Sets the internal parameter related to the fieldname passed to the instance relatedEntity. </summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		/// <param name="fieldName">Name of field mapped onto the relation which resolves in the instance relatedEntity</param>
		protected override void SetRelatedEntity(IEntityCore relatedEntity, string fieldName)
		{
			switch(fieldName)
			{
				case "Assessment":
					SetupSyncAssessment(relatedEntity);
					break;
				case "GoseAccidentTimeframe":
					SetupSyncGoseAccidentTimeframe(relatedEntity);
					break;
				case "GoseFamilyAndFriendshipsDisruptionLevel":
					SetupSyncGoseFamilyAndFriendshipsDisruptionLevel(relatedEntity);
					break;
				case "GoseRespondentType":
					SetupSyncGoseRespondentType(relatedEntity);
					break;
				case "GoseReturnToNormalLifeOutcomeFactor":
					SetupSyncGoseReturnToNormalLifeOutcomeFactor(relatedEntity);
					break;
				case "GoseSocialAndLeisureRestrictionExtent":
					SetupSyncGoseSocialAndLeisureRestrictionExtent(relatedEntity);
					break;
				case "GoseWorkRestrictionLevel":
					SetupSyncGoseWorkRestrictionLevel(relatedEntity);
					break;
				case "CreateUser":
					SetupSyncCreateUser(relatedEntity);
					break;
				case "UpdateUser":
					SetupSyncUpdateUser(relatedEntity);
					break;
				default:
					break;
			}
		}

		/// <summary> Unsets the internal parameter related to the fieldname passed to the instance relatedEntity. Reverses the actions taken by SetRelatedEntity() </summary>
		/// <param name="relatedEntity">Instance to unset as the related entity of type entityType</param>
		/// <param name="fieldName">Name of field mapped onto the relation which resolves in the instance relatedEntity</param>
		/// <param name="signalRelatedEntityManyToOne">if set to true it will notify the manytoone side, if applicable.</param>
		protected override void UnsetRelatedEntity(IEntityCore relatedEntity, string fieldName, bool signalRelatedEntityManyToOne)
		{
			switch(fieldName)
			{
				case "Assessment":
					DesetupSyncAssessment(false, true);
					break;
				case "GoseAccidentTimeframe":
					DesetupSyncGoseAccidentTimeframe(false, true);
					break;
				case "GoseFamilyAndFriendshipsDisruptionLevel":
					DesetupSyncGoseFamilyAndFriendshipsDisruptionLevel(false, true);
					break;
				case "GoseRespondentType":
					DesetupSyncGoseRespondentType(false, true);
					break;
				case "GoseReturnToNormalLifeOutcomeFactor":
					DesetupSyncGoseReturnToNormalLifeOutcomeFactor(false, true);
					break;
				case "GoseSocialAndLeisureRestrictionExtent":
					DesetupSyncGoseSocialAndLeisureRestrictionExtent(false, true);
					break;
				case "GoseWorkRestrictionLevel":
					DesetupSyncGoseWorkRestrictionLevel(false, true);
					break;
				case "CreateUser":
					DesetupSyncCreateUser(false, true);
					break;
				case "UpdateUser":
					DesetupSyncUpdateUser(false, true);
					break;
				default:
					break;
			}
		}

		/// <summary> Gets a collection of related entities referenced by this entity which depend on this entity (this entity is the PK side of their FK fields). These entities will have to be persisted after this entity during a recursive save.</summary>
		/// <returns>Collection with 0 or more IEntity2 objects, referenced by this entity</returns>
		protected override List<IEntity2> GetDependingRelatedEntities()
		{
			List<IEntity2> toReturn = new List<IEntity2>();
			return toReturn;
		}
		
		/// <summary> Gets a collection of related entities referenced by this entity which this entity depends on (this entity is the FK side of their PK fields). These
		/// entities will have to be persisted before this entity during a recursive save.</summary>
		/// <returns>Collection with 0 or more IEntity2 objects, referenced by this entity</returns>
		protected override List<IEntity2> GetDependentRelatedEntities()
		{
			List<IEntity2> toReturn = new List<IEntity2>();
			if(_assessment!=null)
			{
				toReturn.Add(_assessment);
			}
			if(_goseAccidentTimeframe!=null)
			{
				toReturn.Add(_goseAccidentTimeframe);
			}
			if(_goseFamilyAndFriendshipsDisruptionLevel!=null)
			{
				toReturn.Add(_goseFamilyAndFriendshipsDisruptionLevel);
			}
			if(_goseRespondentType!=null)
			{
				toReturn.Add(_goseRespondentType);
			}
			if(_goseReturnToNormalLifeOutcomeFactor!=null)
			{
				toReturn.Add(_goseReturnToNormalLifeOutcomeFactor);
			}
			if(_goseSocialAndLeisureRestrictionExtent!=null)
			{
				toReturn.Add(_goseSocialAndLeisureRestrictionExtent);
			}
			if(_goseWorkRestrictionLevel!=null)
			{
				toReturn.Add(_goseWorkRestrictionLevel);
			}
			if(_createUser!=null)
			{
				toReturn.Add(_createUser);
			}
			if(_updateUser!=null)
			{
				toReturn.Add(_updateUser);
			}
			return toReturn;
		}
		
		/// <summary>Gets a list of all entity collections stored as member variables in this entity. Only 1:n related collections are returned.</summary>
		/// <returns>Collection with 0 or more IEntityCollection2 objects, referenced by this entity</returns>
		protected override List<IEntityCollection2> GetMemberEntityCollections()
		{
			List<IEntityCollection2> toReturn = new List<IEntityCollection2>();
			return toReturn;
		}

		/// <summary>ISerializable member. Does custom serialization so event handlers do not get serialized. Serializes members of this entity class and uses the base class' implementation to serialize the rest.</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		[EditorBrowsable(EditorBrowsableState.Never)]
		protected override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			if (SerializationHelper.Optimization != SerializationOptimization.Fast) 
			{
				info.AddValue("_assessment", (!this.MarkedForDeletion?_assessment:null));
				info.AddValue("_goseAccidentTimeframe", (!this.MarkedForDeletion?_goseAccidentTimeframe:null));
				info.AddValue("_goseFamilyAndFriendshipsDisruptionLevel", (!this.MarkedForDeletion?_goseFamilyAndFriendshipsDisruptionLevel:null));
				info.AddValue("_goseRespondentType", (!this.MarkedForDeletion?_goseRespondentType:null));
				info.AddValue("_goseReturnToNormalLifeOutcomeFactor", (!this.MarkedForDeletion?_goseReturnToNormalLifeOutcomeFactor:null));
				info.AddValue("_goseSocialAndLeisureRestrictionExtent", (!this.MarkedForDeletion?_goseSocialAndLeisureRestrictionExtent:null));
				info.AddValue("_goseWorkRestrictionLevel", (!this.MarkedForDeletion?_goseWorkRestrictionLevel:null));
				info.AddValue("_createUser", (!this.MarkedForDeletion?_createUser:null));
				info.AddValue("_updateUser", (!this.MarkedForDeletion?_updateUser:null));
			}
			// __LLBLGENPRO_USER_CODE_REGION_START GetObjectInfo
			// __LLBLGENPRO_USER_CODE_REGION_END
			base.GetObjectData(info, context);
		}


				
		/// <summary>Gets a list of all the EntityRelation objects the type of this instance has.</summary>
		/// <returns>A list of all the EntityRelation objects the type of this instance has. Hierarchy relations are excluded.</returns>
		protected override List<IEntityRelation> GetAllRelations()
		{
			return new GoseInterviewRelations().GetAllRelations();
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Assessment' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAssessment()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(AssessmentFields.AssessmentId, null, ComparisonOperator.Equal, this.AssessmentId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'GoseAccidentTimeframe' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGoseAccidentTimeframe()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(GoseAccidentTimeframeFields.GoseAccidentTimeframeId, null, ComparisonOperator.Equal, this.AccidentTimeframeId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'GoseFamilyAndFriendshipsDisruptionLevel' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGoseFamilyAndFriendshipsDisruptionLevel()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(GoseFamilyAndFriendshipsDisruptionLevelFields.GoseFamilyAndFriendshipsDisruptionLevelId, null, ComparisonOperator.Equal, this.FamilyAndFriendshipsDisruptionLevelId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'GoseRespondentType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGoseRespondentType()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(GoseRespondentTypeFields.GoseRespondentTypeId, null, ComparisonOperator.Equal, this.RespondentTypeId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'GoseReturnToNormalLifeOutcomeFactor' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGoseReturnToNormalLifeOutcomeFactor()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(GoseReturnToNormalLifeOutcomeFactorFields.GoseReturnToNormalLifeOutcomeFactorId, null, ComparisonOperator.Equal, this.ReturnToNormalLifeMostImportantFactorInOutcomeId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'GoseSocialAndLeisureRestrictionExtent' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGoseSocialAndLeisureRestrictionExtent()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(GoseSocialAndLeisureRestrictionExtentFields.GoseSocialAndLeisureRestrictionExtentId, null, ComparisonOperator.Equal, this.SocialAndLeisureExtentOfRestrictionId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'GoseWorkRestrictionLevel' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGoseWorkRestrictionLevel()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(GoseWorkRestrictionLevelFields.GoseWorkRestrictionLevelId, null, ComparisonOperator.Equal, this.WorkRestrictionLevelId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCreateUser()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(UserFields.UserId, null, ComparisonOperator.Equal, this.CreateUserId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUpdateUser()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(UserFields.UserId, null, ComparisonOperator.Equal, this.UpdateUserId));
			return bucket;
		}
		

		/// <summary>Creates a new instance of the factory related to this entity</summary>
		protected override IEntityFactory2 CreateEntityFactory()
		{
			return EntityFactoryCache2.GetEntityFactory(typeof(GoseInterviewEntityFactory));
		}

		/// <summary>Adds the member collections to the collections queue (base first)</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		protected override void AddToMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue) 
		{
			base.AddToMemberEntityCollectionsQueue(collectionsQueue);
		}
		
		/// <summary>Gets the member collections queue from the queue (base first)</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		protected override void GetFromMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue)
		{
			base.GetFromMemberEntityCollectionsQueue(collectionsQueue);

		}
		
		/// <summary>Determines whether the entity has populated member collections</summary>
		/// <returns>true if the entity has populated member collections.</returns>
		protected override bool HasPopulatedMemberEntityCollections()
		{
			bool toReturn = false;
			return toReturn ? true : base.HasPopulatedMemberEntityCollections();
		}
		
		/// <summary>Creates the member entity collections queue.</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		/// <param name="requiredQueue">The required queue.</param>
		protected override void CreateMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue, Queue<bool> requiredQueue) 
		{
			base.CreateMemberEntityCollectionsQueue(collectionsQueue, requiredQueue);
		}

		/// <summary>Gets all related data objects, stored by name. The name is the field name mapped onto the relation for that particular data element.</summary>
		/// <returns>Dictionary with per name the related referenced data element, which can be an entity collection or an entity or null</returns>
		protected override Dictionary<string, object> GetRelatedData()
		{
			Dictionary<string, object> toReturn = new Dictionary<string, object>();
			toReturn.Add("Assessment", _assessment);
			toReturn.Add("GoseAccidentTimeframe", _goseAccidentTimeframe);
			toReturn.Add("GoseFamilyAndFriendshipsDisruptionLevel", _goseFamilyAndFriendshipsDisruptionLevel);
			toReturn.Add("GoseRespondentType", _goseRespondentType);
			toReturn.Add("GoseReturnToNormalLifeOutcomeFactor", _goseReturnToNormalLifeOutcomeFactor);
			toReturn.Add("GoseSocialAndLeisureRestrictionExtent", _goseSocialAndLeisureRestrictionExtent);
			toReturn.Add("GoseWorkRestrictionLevel", _goseWorkRestrictionLevel);
			toReturn.Add("CreateUser", _createUser);
			toReturn.Add("UpdateUser", _updateUser);
			return toReturn;
		}

		/// <summary> Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}


		#region Custom Property Hashtable Setup
		/// <summary> Initializes the hashtables for the entity type and entity field custom properties. </summary>
		private static void SetupCustomPropertyHashtables()
		{
			_customProperties = new Dictionary<string, string>();
			_fieldsCustomProperties = new Dictionary<string, Dictionary<string, string>>();
			Dictionary<string, string> fieldHashtable;
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("GoseInterviewId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("AssessmentId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("AccidentTimeframeId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("RespondentTypeId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ConciousnessAbleToObeyCommandsOrSpeak", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("IndependenceAtHomeRequireEveryDayAssistance", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("IndependenceAtHomeNeedFrequentHelp", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("IndependenceAtHomeIndependentBeforeInjury", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("IndependenceOutsideHomeAbleToShopWithoutAssistance", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("IndependenceOutsideHomeAbleToShopWithoutAssistanceBeforeInjury", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistance", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistanceBeforeInjury", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("WorkAbleToWorkAtPreviousCapacity", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("WorkRestrictionLevelId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("WorkRestrictionLevelDifferentAfterInjury", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SocialAndLeisureAbleToResumeRegularActivities", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SocialAndLeisureExtentOfRestrictionId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("SocialAndLeisureExtentOfRestrictionDifferentAfterInjury", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("FamilyAndFriendshipsDisruptionDueToPsychologicalProblems", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("FamilyAndFriendshipsDisruptionLevelId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("FamilyAndFriendshipsDisruptionLevelDifferentAfterInjury", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ReturnToNormalLifeAnyOtherCurrentProblems", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ReturnToNormalLifeSimilarProblemsHaveBecomeWorse", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("ReturnToNormalLifeMostImportantFactorInOutcomeId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("CreatedDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("CreateUserId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("UpdateDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("UpdateUserId", fieldHashtable);
		}
		#endregion

		/// <summary> Removes the sync logic for member _assessment</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncAssessment(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _assessment, new PropertyChangedEventHandler(OnAssessmentPropertyChanged), "Assessment", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.AssessmentEntityUsingAssessmentIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.AssessmentId });
		}

		/// <summary> setups the sync logic for member _assessment</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncAssessment(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _assessment, new PropertyChangedEventHandler( OnAssessmentPropertyChanged ), "Assessment", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.AssessmentEntityUsingAssessmentIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.AssessmentId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnAssessmentPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _goseAccidentTimeframe</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncGoseAccidentTimeframe(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _goseAccidentTimeframe, new PropertyChangedEventHandler(OnGoseAccidentTimeframePropertyChanged), "GoseAccidentTimeframe", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseAccidentTimeframeEntityUsingAccidentTimeframeIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.AccidentTimeframeId });
		}

		/// <summary> setups the sync logic for member _goseAccidentTimeframe</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncGoseAccidentTimeframe(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _goseAccidentTimeframe, new PropertyChangedEventHandler( OnGoseAccidentTimeframePropertyChanged ), "GoseAccidentTimeframe", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseAccidentTimeframeEntityUsingAccidentTimeframeIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.AccidentTimeframeId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnGoseAccidentTimeframePropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _goseFamilyAndFriendshipsDisruptionLevel</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncGoseFamilyAndFriendshipsDisruptionLevel(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _goseFamilyAndFriendshipsDisruptionLevel, new PropertyChangedEventHandler(OnGoseFamilyAndFriendshipsDisruptionLevelPropertyChanged), "GoseFamilyAndFriendshipsDisruptionLevel", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseFamilyAndFriendshipsDisruptionLevelEntityUsingFamilyAndFriendshipsDisruptionLevelIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionLevelId });
		}

		/// <summary> setups the sync logic for member _goseFamilyAndFriendshipsDisruptionLevel</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncGoseFamilyAndFriendshipsDisruptionLevel(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _goseFamilyAndFriendshipsDisruptionLevel, new PropertyChangedEventHandler( OnGoseFamilyAndFriendshipsDisruptionLevelPropertyChanged ), "GoseFamilyAndFriendshipsDisruptionLevel", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseFamilyAndFriendshipsDisruptionLevelEntityUsingFamilyAndFriendshipsDisruptionLevelIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionLevelId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnGoseFamilyAndFriendshipsDisruptionLevelPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _goseRespondentType</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncGoseRespondentType(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _goseRespondentType, new PropertyChangedEventHandler(OnGoseRespondentTypePropertyChanged), "GoseRespondentType", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseRespondentTypeEntityUsingRespondentTypeIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.RespondentTypeId });
		}

		/// <summary> setups the sync logic for member _goseRespondentType</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncGoseRespondentType(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _goseRespondentType, new PropertyChangedEventHandler( OnGoseRespondentTypePropertyChanged ), "GoseRespondentType", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseRespondentTypeEntityUsingRespondentTypeIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.RespondentTypeId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnGoseRespondentTypePropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _goseReturnToNormalLifeOutcomeFactor</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncGoseReturnToNormalLifeOutcomeFactor(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _goseReturnToNormalLifeOutcomeFactor, new PropertyChangedEventHandler(OnGoseReturnToNormalLifeOutcomeFactorPropertyChanged), "GoseReturnToNormalLifeOutcomeFactor", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseReturnToNormalLifeOutcomeFactorEntityUsingReturnToNormalLifeMostImportantFactorInOutcomeIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.ReturnToNormalLifeMostImportantFactorInOutcomeId });
		}

		/// <summary> setups the sync logic for member _goseReturnToNormalLifeOutcomeFactor</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncGoseReturnToNormalLifeOutcomeFactor(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _goseReturnToNormalLifeOutcomeFactor, new PropertyChangedEventHandler( OnGoseReturnToNormalLifeOutcomeFactorPropertyChanged ), "GoseReturnToNormalLifeOutcomeFactor", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseReturnToNormalLifeOutcomeFactorEntityUsingReturnToNormalLifeMostImportantFactorInOutcomeIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.ReturnToNormalLifeMostImportantFactorInOutcomeId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnGoseReturnToNormalLifeOutcomeFactorPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _goseSocialAndLeisureRestrictionExtent</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncGoseSocialAndLeisureRestrictionExtent(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _goseSocialAndLeisureRestrictionExtent, new PropertyChangedEventHandler(OnGoseSocialAndLeisureRestrictionExtentPropertyChanged), "GoseSocialAndLeisureRestrictionExtent", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseSocialAndLeisureRestrictionExtentEntityUsingSocialAndLeisureExtentOfRestrictionIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.SocialAndLeisureExtentOfRestrictionId });
		}

		/// <summary> setups the sync logic for member _goseSocialAndLeisureRestrictionExtent</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncGoseSocialAndLeisureRestrictionExtent(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _goseSocialAndLeisureRestrictionExtent, new PropertyChangedEventHandler( OnGoseSocialAndLeisureRestrictionExtentPropertyChanged ), "GoseSocialAndLeisureRestrictionExtent", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseSocialAndLeisureRestrictionExtentEntityUsingSocialAndLeisureExtentOfRestrictionIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.SocialAndLeisureExtentOfRestrictionId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnGoseSocialAndLeisureRestrictionExtentPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _goseWorkRestrictionLevel</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncGoseWorkRestrictionLevel(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _goseWorkRestrictionLevel, new PropertyChangedEventHandler(OnGoseWorkRestrictionLevelPropertyChanged), "GoseWorkRestrictionLevel", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseWorkRestrictionLevelEntityUsingWorkRestrictionLevelIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.WorkRestrictionLevelId });
		}

		/// <summary> setups the sync logic for member _goseWorkRestrictionLevel</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncGoseWorkRestrictionLevel(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _goseWorkRestrictionLevel, new PropertyChangedEventHandler( OnGoseWorkRestrictionLevelPropertyChanged ), "GoseWorkRestrictionLevel", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.GoseWorkRestrictionLevelEntityUsingWorkRestrictionLevelIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.WorkRestrictionLevelId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnGoseWorkRestrictionLevelPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _createUser</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncCreateUser(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _createUser, new PropertyChangedEventHandler(OnCreateUserPropertyChanged), "CreateUser", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.UserEntityUsingCreateUserIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.CreateUserId });
		}

		/// <summary> setups the sync logic for member _createUser</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncCreateUser(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _createUser, new PropertyChangedEventHandler( OnCreateUserPropertyChanged ), "CreateUser", "GoseInterviews", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.UserEntityUsingCreateUserIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.CreateUserId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnCreateUserPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _updateUser</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncUpdateUser(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _updateUser, new PropertyChangedEventHandler(OnUpdateUserPropertyChanged), "UpdateUser", "GoseInterviews1", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.UserEntityUsingUpdateUserIdStatic, true, new int[] { (int)GoseInterviewFieldIndex.UpdateUserId });
		}

		/// <summary> setups the sync logic for member _updateUser</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncUpdateUser(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _updateUser, new PropertyChangedEventHandler( OnUpdateUserPropertyChanged ), "UpdateUser", "GoseInterviews1", PsychologicalServices.Data.RelationClasses.StaticGoseInterviewRelations.UserEntityUsingUpdateUserIdStatic, true, new string[] {  }, new int[] { (int)GoseInterviewFieldIndex.UpdateUserId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnUpdateUserPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this GoseInterviewEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();

			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();

		}

		#region Class Property Declarations
		/// <summary> The relations object holding all relations of this entity with other entity classes.</summary>
		public  static GoseInterviewRelations Relations
		{
			get	{ return new GoseInterviewRelations(); }
		}
		
		/// <summary> The custom properties for this entity type.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, string> CustomProperties
		{
			get { return _customProperties;}
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Assessment' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAssessment
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(AssessmentEntityFactory))),	(IEntityRelation)GetRelationsForField("Assessment")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.AssessmentEntity, 0, null, null, null, null, "Assessment", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'GoseAccidentTimeframe' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGoseAccidentTimeframe
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(GoseAccidentTimeframeEntityFactory))),	(IEntityRelation)GetRelationsForField("GoseAccidentTimeframe")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.GoseAccidentTimeframeEntity, 0, null, null, null, null, "GoseAccidentTimeframe", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'GoseFamilyAndFriendshipsDisruptionLevel' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGoseFamilyAndFriendshipsDisruptionLevel
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(GoseFamilyAndFriendshipsDisruptionLevelEntityFactory))),	(IEntityRelation)GetRelationsForField("GoseFamilyAndFriendshipsDisruptionLevel")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.GoseFamilyAndFriendshipsDisruptionLevelEntity, 0, null, null, null, null, "GoseFamilyAndFriendshipsDisruptionLevel", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'GoseRespondentType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGoseRespondentType
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(GoseRespondentTypeEntityFactory))),	(IEntityRelation)GetRelationsForField("GoseRespondentType")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.GoseRespondentTypeEntity, 0, null, null, null, null, "GoseRespondentType", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'GoseReturnToNormalLifeOutcomeFactor' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGoseReturnToNormalLifeOutcomeFactor
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(GoseReturnToNormalLifeOutcomeFactorEntityFactory))),	(IEntityRelation)GetRelationsForField("GoseReturnToNormalLifeOutcomeFactor")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.GoseReturnToNormalLifeOutcomeFactorEntity, 0, null, null, null, null, "GoseReturnToNormalLifeOutcomeFactor", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'GoseSocialAndLeisureRestrictionExtent' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGoseSocialAndLeisureRestrictionExtent
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(GoseSocialAndLeisureRestrictionExtentEntityFactory))),	(IEntityRelation)GetRelationsForField("GoseSocialAndLeisureRestrictionExtent")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.GoseSocialAndLeisureRestrictionExtentEntity, 0, null, null, null, null, "GoseSocialAndLeisureRestrictionExtent", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'GoseWorkRestrictionLevel' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGoseWorkRestrictionLevel
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(GoseWorkRestrictionLevelEntityFactory))),	(IEntityRelation)GetRelationsForField("GoseWorkRestrictionLevel")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.GoseWorkRestrictionLevelEntity, 0, null, null, null, null, "GoseWorkRestrictionLevel", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCreateUser
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(UserEntityFactory))),	(IEntityRelation)GetRelationsForField("CreateUser")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.UserEntity, 0, null, null, null, null, "CreateUser", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUpdateUser
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(UserEntityFactory))),	(IEntityRelation)GetRelationsForField("UpdateUser")[0], (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity, (int)PsychologicalServices.Data.EntityType.UserEntity, 0, null, null, null, null, "UpdateUser", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}


		/// <summary> The custom properties for the type of this entity instance.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, string> CustomPropertiesOfType
		{
			get { return CustomProperties;}
		}

		/// <summary> The custom properties for the fields of this entity type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, Dictionary<string, string>> FieldsCustomProperties
		{
			get { return _fieldsCustomProperties;}
		}

		/// <summary> The custom properties for the fields of the type of this entity instance. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType
		{
			get { return FieldsCustomProperties;}
		}

		/// <summary> The GoseInterviewId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."GoseInterviewId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 GoseInterviewId
		{
			get { return (System.Int32)GetValue((int)GoseInterviewFieldIndex.GoseInterviewId, true); }
			set	{ SetValue((int)GoseInterviewFieldIndex.GoseInterviewId, value); }
		}

		/// <summary> The AssessmentId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."AssessmentId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 AssessmentId
		{
			get { return (System.Int32)GetValue((int)GoseInterviewFieldIndex.AssessmentId, true); }
			set	{ SetValue((int)GoseInterviewFieldIndex.AssessmentId, value); }
		}

		/// <summary> The AccidentTimeframeId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."AccidentTimeframeId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AccidentTimeframeId
		{
			get { return (Nullable<System.Int32>)GetValue((int)GoseInterviewFieldIndex.AccidentTimeframeId, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.AccidentTimeframeId, value); }
		}

		/// <summary> The RespondentTypeId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."RespondentTypeId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> RespondentTypeId
		{
			get { return (Nullable<System.Int32>)GetValue((int)GoseInterviewFieldIndex.RespondentTypeId, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.RespondentTypeId, value); }
		}

		/// <summary> The ConciousnessAbleToObeyCommandsOrSpeak property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."ConciousnessAbleToObeyCommandsOrSpeak"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> ConciousnessAbleToObeyCommandsOrSpeak
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.ConciousnessAbleToObeyCommandsOrSpeak, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.ConciousnessAbleToObeyCommandsOrSpeak, value); }
		}

		/// <summary> The IndependenceAtHomeRequireEveryDayAssistance property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."IndependenceAtHomeRequireEveryDayAssistance"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IndependenceAtHomeRequireEveryDayAssistance
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.IndependenceAtHomeRequireEveryDayAssistance, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.IndependenceAtHomeRequireEveryDayAssistance, value); }
		}

		/// <summary> The IndependenceAtHomeNeedFrequentHelp property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."IndependenceAtHomeNeedFrequentHelp"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IndependenceAtHomeNeedFrequentHelp
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.IndependenceAtHomeNeedFrequentHelp, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.IndependenceAtHomeNeedFrequentHelp, value); }
		}

		/// <summary> The IndependenceAtHomeIndependentBeforeInjury property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."IndependenceAtHomeIndependentBeforeInjury"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IndependenceAtHomeIndependentBeforeInjury
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.IndependenceAtHomeIndependentBeforeInjury, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.IndependenceAtHomeIndependentBeforeInjury, value); }
		}

		/// <summary> The IndependenceOutsideHomeAbleToShopWithoutAssistance property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."IndependenceOutsideHomeAbleToShopWithoutAssistance"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IndependenceOutsideHomeAbleToShopWithoutAssistance
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToShopWithoutAssistance, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToShopWithoutAssistance, value); }
		}

		/// <summary> The IndependenceOutsideHomeAbleToShopWithoutAssistanceBeforeInjury property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."IndependenceOutsideHomeAbleToShopWithoutAssistanceBeforeInjury"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IndependenceOutsideHomeAbleToShopWithoutAssistanceBeforeInjury
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToShopWithoutAssistanceBeforeInjury, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToShopWithoutAssistanceBeforeInjury, value); }
		}

		/// <summary> The IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistance property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistance"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistance
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistance, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistance, value); }
		}

		/// <summary> The IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistanceBeforeInjury property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistanceBeforeInjury"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistanceBeforeInjury
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistanceBeforeInjury, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.IndependenceOutsideHomeAbleToTravelLocallyWithoutAssistanceBeforeInjury, value); }
		}

		/// <summary> The WorkAbleToWorkAtPreviousCapacity property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."WorkAbleToWorkAtPreviousCapacity"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> WorkAbleToWorkAtPreviousCapacity
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.WorkAbleToWorkAtPreviousCapacity, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.WorkAbleToWorkAtPreviousCapacity, value); }
		}

		/// <summary> The WorkRestrictionLevelId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."WorkRestrictionLevelId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> WorkRestrictionLevelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)GoseInterviewFieldIndex.WorkRestrictionLevelId, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.WorkRestrictionLevelId, value); }
		}

		/// <summary> The WorkRestrictionLevelDifferentAfterInjury property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."WorkRestrictionLevelDifferentAfterInjury"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> WorkRestrictionLevelDifferentAfterInjury
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.WorkRestrictionLevelDifferentAfterInjury, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.WorkRestrictionLevelDifferentAfterInjury, value); }
		}

		/// <summary> The SocialAndLeisureAbleToResumeRegularActivities property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."SocialAndLeisureAbleToResumeRegularActivities"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> SocialAndLeisureAbleToResumeRegularActivities
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.SocialAndLeisureAbleToResumeRegularActivities, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.SocialAndLeisureAbleToResumeRegularActivities, value); }
		}

		/// <summary> The SocialAndLeisureExtentOfRestrictionId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."SocialAndLeisureExtentOfRestrictionId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SocialAndLeisureExtentOfRestrictionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)GoseInterviewFieldIndex.SocialAndLeisureExtentOfRestrictionId, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.SocialAndLeisureExtentOfRestrictionId, value); }
		}

		/// <summary> The SocialAndLeisureExtentOfRestrictionDifferentAfterInjury property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."SocialAndLeisureExtentOfRestrictionDifferentAfterInjury"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> SocialAndLeisureExtentOfRestrictionDifferentAfterInjury
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.SocialAndLeisureExtentOfRestrictionDifferentAfterInjury, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.SocialAndLeisureExtentOfRestrictionDifferentAfterInjury, value); }
		}

		/// <summary> The FamilyAndFriendshipsDisruptionDueToPsychologicalProblems property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."FamilyAndFriendshipsDisruptionDueToPsychologicalProblems"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> FamilyAndFriendshipsDisruptionDueToPsychologicalProblems
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionDueToPsychologicalProblems, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionDueToPsychologicalProblems, value); }
		}

		/// <summary> The FamilyAndFriendshipsDisruptionLevelId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."FamilyAndFriendshipsDisruptionLevelId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> FamilyAndFriendshipsDisruptionLevelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionLevelId, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionLevelId, value); }
		}

		/// <summary> The FamilyAndFriendshipsDisruptionLevelDifferentAfterInjury property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."FamilyAndFriendshipsDisruptionLevelDifferentAfterInjury"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> FamilyAndFriendshipsDisruptionLevelDifferentAfterInjury
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionLevelDifferentAfterInjury, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.FamilyAndFriendshipsDisruptionLevelDifferentAfterInjury, value); }
		}

		/// <summary> The ReturnToNormalLifeAnyOtherCurrentProblems property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."ReturnToNormalLifeAnyOtherCurrentProblems"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> ReturnToNormalLifeAnyOtherCurrentProblems
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.ReturnToNormalLifeAnyOtherCurrentProblems, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.ReturnToNormalLifeAnyOtherCurrentProblems, value); }
		}

		/// <summary> The ReturnToNormalLifeSimilarProblemsHaveBecomeWorse property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."ReturnToNormalLifeSimilarProblemsHaveBecomeWorse"<br/>
		/// Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> ReturnToNormalLifeSimilarProblemsHaveBecomeWorse
		{
			get { return (Nullable<System.Boolean>)GetValue((int)GoseInterviewFieldIndex.ReturnToNormalLifeSimilarProblemsHaveBecomeWorse, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.ReturnToNormalLifeSimilarProblemsHaveBecomeWorse, value); }
		}

		/// <summary> The ReturnToNormalLifeMostImportantFactorInOutcomeId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."ReturnToNormalLifeMostImportantFactorInOutcomeId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ReturnToNormalLifeMostImportantFactorInOutcomeId
		{
			get { return (Nullable<System.Int32>)GetValue((int)GoseInterviewFieldIndex.ReturnToNormalLifeMostImportantFactorInOutcomeId, false); }
			set	{ SetValue((int)GoseInterviewFieldIndex.ReturnToNormalLifeMostImportantFactorInOutcomeId, value); }
		}

		/// <summary> The CreatedDate property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."CreatedDate"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTimeOffset, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTimeOffset CreatedDate
		{
			get { return (System.DateTimeOffset)GetValue((int)GoseInterviewFieldIndex.CreatedDate, true); }
			set	{ SetValue((int)GoseInterviewFieldIndex.CreatedDate, value); }
		}

		/// <summary> The CreateUserId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."CreateUserId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 CreateUserId
		{
			get { return (System.Int32)GetValue((int)GoseInterviewFieldIndex.CreateUserId, true); }
			set	{ SetValue((int)GoseInterviewFieldIndex.CreateUserId, value); }
		}

		/// <summary> The UpdateDate property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."UpdateDate"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTimeOffset, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTimeOffset UpdateDate
		{
			get { return (System.DateTimeOffset)GetValue((int)GoseInterviewFieldIndex.UpdateDate, true); }
			set	{ SetValue((int)GoseInterviewFieldIndex.UpdateDate, value); }
		}

		/// <summary> The UpdateUserId property of the Entity GoseInterview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "GoseInterviews"."UpdateUserId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UpdateUserId
		{
			get { return (System.Int32)GetValue((int)GoseInterviewFieldIndex.UpdateUserId, true); }
			set	{ SetValue((int)GoseInterviewFieldIndex.UpdateUserId, value); }
		}

		/// <summary> Gets / sets related entity of type 'AssessmentEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AssessmentEntity Assessment
		{
			get	{ return _assessment; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncAssessment(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "Assessment", _assessment, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'GoseAccidentTimeframeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual GoseAccidentTimeframeEntity GoseAccidentTimeframe
		{
			get	{ return _goseAccidentTimeframe; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncGoseAccidentTimeframe(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "GoseAccidentTimeframe", _goseAccidentTimeframe, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'GoseFamilyAndFriendshipsDisruptionLevelEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual GoseFamilyAndFriendshipsDisruptionLevelEntity GoseFamilyAndFriendshipsDisruptionLevel
		{
			get	{ return _goseFamilyAndFriendshipsDisruptionLevel; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncGoseFamilyAndFriendshipsDisruptionLevel(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "GoseFamilyAndFriendshipsDisruptionLevel", _goseFamilyAndFriendshipsDisruptionLevel, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'GoseRespondentTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual GoseRespondentTypeEntity GoseRespondentType
		{
			get	{ return _goseRespondentType; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncGoseRespondentType(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "GoseRespondentType", _goseRespondentType, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'GoseReturnToNormalLifeOutcomeFactorEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual GoseReturnToNormalLifeOutcomeFactorEntity GoseReturnToNormalLifeOutcomeFactor
		{
			get	{ return _goseReturnToNormalLifeOutcomeFactor; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncGoseReturnToNormalLifeOutcomeFactor(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "GoseReturnToNormalLifeOutcomeFactor", _goseReturnToNormalLifeOutcomeFactor, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'GoseSocialAndLeisureRestrictionExtentEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual GoseSocialAndLeisureRestrictionExtentEntity GoseSocialAndLeisureRestrictionExtent
		{
			get	{ return _goseSocialAndLeisureRestrictionExtent; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncGoseSocialAndLeisureRestrictionExtent(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "GoseSocialAndLeisureRestrictionExtent", _goseSocialAndLeisureRestrictionExtent, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'GoseWorkRestrictionLevelEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual GoseWorkRestrictionLevelEntity GoseWorkRestrictionLevel
		{
			get	{ return _goseWorkRestrictionLevel; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncGoseWorkRestrictionLevel(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "GoseWorkRestrictionLevel", _goseWorkRestrictionLevel, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual UserEntity CreateUser
		{
			get	{ return _createUser; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncCreateUser(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews", "CreateUser", _createUser, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual UserEntity UpdateUser
		{
			get	{ return _updateUser; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncUpdateUser(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "GoseInterviews1", "UpdateUser", _updateUser, true); 
				}
			}
		}
	
		/// <summary> Gets the type of the hierarchy this entity is in. </summary>
		protected override InheritanceHierarchyType LLBLGenProIsInHierarchyOfType
		{
			get { return InheritanceHierarchyType.None;}
		}
		
		/// <summary> Gets or sets a value indicating whether this entity is a subtype</summary>
		protected override bool LLBLGenProIsSubType
		{
			get { return false;}
		}
		
		/// <summary>Returns the PsychologicalServices.Data.EntityType enum value for this entity.</summary>
		[Browsable(false), XmlIgnore]
		protected override int LLBLGenProEntityTypeValue 
		{ 
			get { return (int)PsychologicalServices.Data.EntityType.GoseInterviewEntity; }
		}

		#endregion


		#region Custom Entity code
		
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END
		#endregion

		#region Included code

		#endregion
	}
}
