//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using PsychologicalServices.Data;
using PsychologicalServices.Data.HelperClasses;
using PsychologicalServices.Data.FactoryClasses;
using PsychologicalServices.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PsychologicalServices.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Invoice'.<br/><br/></summary>
	[Serializable]
	public partial class InvoiceEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		#region Class Member Declarations
		private EntityCollection<InvoiceDocumentEntity> _invoiceDocuments;
		private EntityCollection<InvoiceLineGroupEntity> _invoiceLineGroups;
		private EntityCollection<InvoiceStatusChangeEntity> _invoiceStatusChanges;
		private InvoiceStatusEntity _invoiceStatus;
		private InvoiceTypeEntity _invoiceType;
		private UserEntity _payableTo;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		#endregion

		#region Statics
		private static Dictionary<string, string>	_customProperties;
		private static Dictionary<string, Dictionary<string, string>>	_fieldsCustomProperties;

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name InvoiceStatus</summary>
			public static readonly string InvoiceStatus = "InvoiceStatus";
			/// <summary>Member name InvoiceType</summary>
			public static readonly string InvoiceType = "InvoiceType";
			/// <summary>Member name PayableTo</summary>
			public static readonly string PayableTo = "PayableTo";
			/// <summary>Member name InvoiceDocuments</summary>
			public static readonly string InvoiceDocuments = "InvoiceDocuments";
			/// <summary>Member name InvoiceLineGroups</summary>
			public static readonly string InvoiceLineGroups = "InvoiceLineGroups";
			/// <summary>Member name InvoiceStatusChanges</summary>
			public static readonly string InvoiceStatusChanges = "InvoiceStatusChanges";
		}
		#endregion
		
		/// <summary> Static CTor for setting up custom property hashtables. Is executed before the first instance of this entity class or derived classes is constructed. </summary>
		static InvoiceEntity()
		{
			SetupCustomPropertyHashtables();
		}
		
		/// <summary> CTor</summary>
		public InvoiceEntity():base("InvoiceEntity")
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <remarks>For framework usage.</remarks>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public InvoiceEntity(IEntityFields2 fields):base("InvoiceEntity")
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this InvoiceEntity</param>
		public InvoiceEntity(IValidator validator):base("InvoiceEntity")
		{
			InitClassEmpty(validator, null);
		}
				
		/// <summary> CTor</summary>
		/// <param name="invoiceId">PK value for Invoice which data should be fetched into this Invoice object</param>
		/// <remarks>The entity is not fetched by this constructor. Use a DataAccessAdapter for that.</remarks>
		public InvoiceEntity(System.Int32 invoiceId):base("InvoiceEntity")
		{
			InitClassEmpty(null, null);
			this.InvoiceId = invoiceId;
		}

		/// <summary> CTor</summary>
		/// <param name="invoiceId">PK value for Invoice which data should be fetched into this Invoice object</param>
		/// <param name="validator">The custom validator object for this InvoiceEntity</param>
		/// <remarks>The entity is not fetched by this constructor. Use a DataAccessAdapter for that.</remarks>
		public InvoiceEntity(System.Int32 invoiceId, IValidator validator):base("InvoiceEntity")
		{
			InitClassEmpty(validator, null);
			this.InvoiceId = invoiceId;
		}

		/// <summary> Protected CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		[EditorBrowsable(EditorBrowsableState.Never)]
		protected InvoiceEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			if(SerializationHelper.Optimization != SerializationOptimization.Fast) 
			{
				_invoiceDocuments = (EntityCollection<InvoiceDocumentEntity>)info.GetValue("_invoiceDocuments", typeof(EntityCollection<InvoiceDocumentEntity>));
				_invoiceLineGroups = (EntityCollection<InvoiceLineGroupEntity>)info.GetValue("_invoiceLineGroups", typeof(EntityCollection<InvoiceLineGroupEntity>));
				_invoiceStatusChanges = (EntityCollection<InvoiceStatusChangeEntity>)info.GetValue("_invoiceStatusChanges", typeof(EntityCollection<InvoiceStatusChangeEntity>));
				_invoiceStatus = (InvoiceStatusEntity)info.GetValue("_invoiceStatus", typeof(InvoiceStatusEntity));
				if(_invoiceStatus!=null)
				{
					_invoiceStatus.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_invoiceType = (InvoiceTypeEntity)info.GetValue("_invoiceType", typeof(InvoiceTypeEntity));
				if(_invoiceType!=null)
				{
					_invoiceType.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				_payableTo = (UserEntity)info.GetValue("_payableTo", typeof(UserEntity));
				if(_payableTo!=null)
				{
					_payableTo.AfterSave+=new EventHandler(OnEntityAfterSave);
				}
				this.FixupDeserialization(FieldInfoProviderSingleton.GetInstance());
			}
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		
		/// <summary>Performs the desync setup when an FK field has been changed. The entity referenced based on the FK field will be dereferenced and sync info will be removed.</summary>
		/// <param name="fieldIndex">The fieldindex.</param>
		protected override void PerformDesyncSetupFKFieldChange(int fieldIndex)
		{
			switch((InvoiceFieldIndex)fieldIndex)
			{
				case InvoiceFieldIndex.InvoiceStatusId:
					DesetupSyncInvoiceStatus(true, false);
					break;
				case InvoiceFieldIndex.InvoiceTypeId:
					DesetupSyncInvoiceType(true, false);
					break;
				case InvoiceFieldIndex.PayableToId:
					DesetupSyncPayableTo(true, false);
					break;
				default:
					base.PerformDesyncSetupFKFieldChange(fieldIndex);
					break;
			}
		}

		/// <summary> Sets the related entity property to the entity specified. If the property is a collection, it will add the entity specified to that collection.</summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <param name="entity">Entity to set as an related entity</param>
		/// <remarks>Used by prefetch path logic.</remarks>
		protected override void SetRelatedEntityProperty(string propertyName, IEntityCore entity)
		{
			switch(propertyName)
			{
				case "InvoiceStatus":
					this.InvoiceStatus = (InvoiceStatusEntity)entity;
					break;
				case "InvoiceType":
					this.InvoiceType = (InvoiceTypeEntity)entity;
					break;
				case "PayableTo":
					this.PayableTo = (UserEntity)entity;
					break;
				case "InvoiceDocuments":
					this.InvoiceDocuments.Add((InvoiceDocumentEntity)entity);
					break;
				case "InvoiceLineGroups":
					this.InvoiceLineGroups.Add((InvoiceLineGroupEntity)entity);
					break;
				case "InvoiceStatusChanges":
					this.InvoiceStatusChanges.Add((InvoiceStatusChangeEntity)entity);
					break;
				default:
					this.OnSetRelatedEntityProperty(propertyName, entity);
					break;
			}
		}
		
		/// <summary>Gets the relation objects which represent the relation the fieldName specified is mapped on. </summary>
		/// <param name="fieldName">Name of the field mapped onto the relation of which the relation objects have to be obtained.</param>
		/// <returns>RelationCollection with relation object(s) which represent the relation the field is maped on</returns>
		protected override RelationCollection GetRelationsForFieldOfType(string fieldName)
		{
			return GetRelationsForField(fieldName);
		}

		/// <summary>Gets the relation objects which represent the relation the fieldName specified is mapped on. </summary>
		/// <param name="fieldName">Name of the field mapped onto the relation of which the relation objects have to be obtained.</param>
		/// <returns>RelationCollection with relation object(s) which represent the relation the field is maped on</returns>
		internal static RelationCollection GetRelationsForField(string fieldName)
		{
			RelationCollection toReturn = new RelationCollection();
			switch(fieldName)
			{
				case "InvoiceStatus":
					toReturn.Add(Relations.InvoiceStatusEntityUsingInvoiceStatusId);
					break;
				case "InvoiceType":
					toReturn.Add(Relations.InvoiceTypeEntityUsingInvoiceTypeId);
					break;
				case "PayableTo":
					toReturn.Add(Relations.UserEntityUsingPayableToId);
					break;
				case "InvoiceDocuments":
					toReturn.Add(Relations.InvoiceDocumentEntityUsingInvoiceId);
					break;
				case "InvoiceLineGroups":
					toReturn.Add(Relations.InvoiceLineGroupEntityUsingInvoiceId);
					break;
				case "InvoiceStatusChanges":
					toReturn.Add(Relations.InvoiceStatusChangeEntityUsingInvoiceId);
					break;
				default:
					break;				
			}
			return toReturn;
		}

		/// <summary>Checks if the relation mapped by the property with the name specified is a one way / single sided relation. If the passed in name is null, it/ will return true if the entity has any single-sided relation</summary>
		/// <param name="propertyName">Name of the property which is mapped onto the relation to check, or null to check if the entity has any relation/ which is single sided</param>
		/// <returns>true if the relation is single sided / one way (so the opposite relation isn't present), false otherwise</returns>
		protected override bool CheckOneWayRelations(string propertyName)
		{
			int numberOfOneWayRelations = 0;
			switch(propertyName)
			{
				case null:
					return ((numberOfOneWayRelations > 0) || base.CheckOneWayRelations(null));
				default:
					return base.CheckOneWayRelations(propertyName);
			}
		}

		/// <summary> Sets the internal parameter related to the fieldname passed to the instance relatedEntity. </summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		/// <param name="fieldName">Name of field mapped onto the relation which resolves in the instance relatedEntity</param>
		protected override void SetRelatedEntity(IEntityCore relatedEntity, string fieldName)
		{
			switch(fieldName)
			{
				case "InvoiceStatus":
					SetupSyncInvoiceStatus(relatedEntity);
					break;
				case "InvoiceType":
					SetupSyncInvoiceType(relatedEntity);
					break;
				case "PayableTo":
					SetupSyncPayableTo(relatedEntity);
					break;
				case "InvoiceDocuments":
					this.InvoiceDocuments.Add((InvoiceDocumentEntity)relatedEntity);
					break;
				case "InvoiceLineGroups":
					this.InvoiceLineGroups.Add((InvoiceLineGroupEntity)relatedEntity);
					break;
				case "InvoiceStatusChanges":
					this.InvoiceStatusChanges.Add((InvoiceStatusChangeEntity)relatedEntity);
					break;
				default:
					break;
			}
		}

		/// <summary> Unsets the internal parameter related to the fieldname passed to the instance relatedEntity. Reverses the actions taken by SetRelatedEntity() </summary>
		/// <param name="relatedEntity">Instance to unset as the related entity of type entityType</param>
		/// <param name="fieldName">Name of field mapped onto the relation which resolves in the instance relatedEntity</param>
		/// <param name="signalRelatedEntityManyToOne">if set to true it will notify the manytoone side, if applicable.</param>
		protected override void UnsetRelatedEntity(IEntityCore relatedEntity, string fieldName, bool signalRelatedEntityManyToOne)
		{
			switch(fieldName)
			{
				case "InvoiceStatus":
					DesetupSyncInvoiceStatus(false, true);
					break;
				case "InvoiceType":
					DesetupSyncInvoiceType(false, true);
					break;
				case "PayableTo":
					DesetupSyncPayableTo(false, true);
					break;
				case "InvoiceDocuments":
					this.PerformRelatedEntityRemoval(this.InvoiceDocuments, relatedEntity, signalRelatedEntityManyToOne);
					break;
				case "InvoiceLineGroups":
					this.PerformRelatedEntityRemoval(this.InvoiceLineGroups, relatedEntity, signalRelatedEntityManyToOne);
					break;
				case "InvoiceStatusChanges":
					this.PerformRelatedEntityRemoval(this.InvoiceStatusChanges, relatedEntity, signalRelatedEntityManyToOne);
					break;
				default:
					break;
			}
		}

		/// <summary> Gets a collection of related entities referenced by this entity which depend on this entity (this entity is the PK side of their FK fields). These entities will have to be persisted after this entity during a recursive save.</summary>
		/// <returns>Collection with 0 or more IEntity2 objects, referenced by this entity</returns>
		protected override List<IEntity2> GetDependingRelatedEntities()
		{
			List<IEntity2> toReturn = new List<IEntity2>();
			return toReturn;
		}
		
		/// <summary> Gets a collection of related entities referenced by this entity which this entity depends on (this entity is the FK side of their PK fields). These
		/// entities will have to be persisted before this entity during a recursive save.</summary>
		/// <returns>Collection with 0 or more IEntity2 objects, referenced by this entity</returns>
		protected override List<IEntity2> GetDependentRelatedEntities()
		{
			List<IEntity2> toReturn = new List<IEntity2>();
			if(_invoiceStatus!=null)
			{
				toReturn.Add(_invoiceStatus);
			}
			if(_invoiceType!=null)
			{
				toReturn.Add(_invoiceType);
			}
			if(_payableTo!=null)
			{
				toReturn.Add(_payableTo);
			}
			return toReturn;
		}
		
		/// <summary>Gets a list of all entity collections stored as member variables in this entity. Only 1:n related collections are returned.</summary>
		/// <returns>Collection with 0 or more IEntityCollection2 objects, referenced by this entity</returns>
		protected override List<IEntityCollection2> GetMemberEntityCollections()
		{
			List<IEntityCollection2> toReturn = new List<IEntityCollection2>();
			toReturn.Add(this.InvoiceDocuments);
			toReturn.Add(this.InvoiceLineGroups);
			toReturn.Add(this.InvoiceStatusChanges);
			return toReturn;
		}

		/// <summary>ISerializable member. Does custom serialization so event handlers do not get serialized. Serializes members of this entity class and uses the base class' implementation to serialize the rest.</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		[EditorBrowsable(EditorBrowsableState.Never)]
		protected override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			if (SerializationHelper.Optimization != SerializationOptimization.Fast) 
			{
				info.AddValue("_invoiceDocuments", ((_invoiceDocuments!=null) && (_invoiceDocuments.Count>0) && !this.MarkedForDeletion)?_invoiceDocuments:null);
				info.AddValue("_invoiceLineGroups", ((_invoiceLineGroups!=null) && (_invoiceLineGroups.Count>0) && !this.MarkedForDeletion)?_invoiceLineGroups:null);
				info.AddValue("_invoiceStatusChanges", ((_invoiceStatusChanges!=null) && (_invoiceStatusChanges.Count>0) && !this.MarkedForDeletion)?_invoiceStatusChanges:null);
				info.AddValue("_invoiceStatus", (!this.MarkedForDeletion?_invoiceStatus:null));
				info.AddValue("_invoiceType", (!this.MarkedForDeletion?_invoiceType:null));
				info.AddValue("_payableTo", (!this.MarkedForDeletion?_payableTo:null));
			}
			// __LLBLGENPRO_USER_CODE_REGION_START GetObjectInfo
			// __LLBLGENPRO_USER_CODE_REGION_END
			base.GetObjectData(info, context);
		}


				
		/// <summary>Gets a list of all the EntityRelation objects the type of this instance has.</summary>
		/// <returns>A list of all the EntityRelation objects the type of this instance has. Hierarchy relations are excluded.</returns>
		protected override List<IEntityRelation> GetAllRelations()
		{
			return new InvoiceRelations().GetAllRelations();
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'InvoiceDocument' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInvoiceDocuments()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(InvoiceDocumentFields.InvoiceId, null, ComparisonOperator.Equal, this.InvoiceId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'InvoiceLineGroup' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInvoiceLineGroups()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(InvoiceLineGroupFields.InvoiceId, null, ComparisonOperator.Equal, this.InvoiceId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'InvoiceStatusChange' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInvoiceStatusChanges()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(InvoiceStatusChangeFields.InvoiceId, null, ComparisonOperator.Equal, this.InvoiceId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'InvoiceStatus' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInvoiceStatus()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(InvoiceStatusFields.InvoiceStatusId, null, ComparisonOperator.Equal, this.InvoiceStatusId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'InvoiceType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInvoiceType()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(InvoiceTypeFields.InvoiceTypeId, null, ComparisonOperator.Equal, this.InvoiceTypeId));
			return bucket;
		}

		/// <summary> Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPayableTo()
		{
			IRelationPredicateBucket bucket = new RelationPredicateBucket();
			bucket.PredicateExpression.Add(new FieldCompareValuePredicate(UserFields.UserId, null, ComparisonOperator.Equal, this.PayableToId));
			return bucket;
		}
		

		/// <summary>Creates a new instance of the factory related to this entity</summary>
		protected override IEntityFactory2 CreateEntityFactory()
		{
			return EntityFactoryCache2.GetEntityFactory(typeof(InvoiceEntityFactory));
		}

		/// <summary>Adds the member collections to the collections queue (base first)</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		protected override void AddToMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue) 
		{
			base.AddToMemberEntityCollectionsQueue(collectionsQueue);
			collectionsQueue.Enqueue(this._invoiceDocuments);
			collectionsQueue.Enqueue(this._invoiceLineGroups);
			collectionsQueue.Enqueue(this._invoiceStatusChanges);
		}
		
		/// <summary>Gets the member collections queue from the queue (base first)</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		protected override void GetFromMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue)
		{
			base.GetFromMemberEntityCollectionsQueue(collectionsQueue);
			this._invoiceDocuments = (EntityCollection<InvoiceDocumentEntity>) collectionsQueue.Dequeue();
			this._invoiceLineGroups = (EntityCollection<InvoiceLineGroupEntity>) collectionsQueue.Dequeue();
			this._invoiceStatusChanges = (EntityCollection<InvoiceStatusChangeEntity>) collectionsQueue.Dequeue();

		}
		
		/// <summary>Determines whether the entity has populated member collections</summary>
		/// <returns>true if the entity has populated member collections.</returns>
		protected override bool HasPopulatedMemberEntityCollections()
		{
			bool toReturn = false;
			toReturn |=(this._invoiceDocuments != null);
			toReturn |=(this._invoiceLineGroups != null);
			toReturn |=(this._invoiceStatusChanges != null);
			return toReturn ? true : base.HasPopulatedMemberEntityCollections();
		}
		
		/// <summary>Creates the member entity collections queue.</summary>
		/// <param name="collectionsQueue">The collections queue.</param>
		/// <param name="requiredQueue">The required queue.</param>
		protected override void CreateMemberEntityCollectionsQueue(Queue<IEntityCollection2> collectionsQueue, Queue<bool> requiredQueue) 
		{
			base.CreateMemberEntityCollectionsQueue(collectionsQueue, requiredQueue);
			collectionsQueue.Enqueue(requiredQueue.Dequeue() ? new EntityCollection<InvoiceDocumentEntity>(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceDocumentEntityFactory))) : null);
			collectionsQueue.Enqueue(requiredQueue.Dequeue() ? new EntityCollection<InvoiceLineGroupEntity>(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceLineGroupEntityFactory))) : null);
			collectionsQueue.Enqueue(requiredQueue.Dequeue() ? new EntityCollection<InvoiceStatusChangeEntity>(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceStatusChangeEntityFactory))) : null);
		}

		/// <summary>Gets all related data objects, stored by name. The name is the field name mapped onto the relation for that particular data element.</summary>
		/// <returns>Dictionary with per name the related referenced data element, which can be an entity collection or an entity or null</returns>
		protected override Dictionary<string, object> GetRelatedData()
		{
			Dictionary<string, object> toReturn = new Dictionary<string, object>();
			toReturn.Add("InvoiceStatus", _invoiceStatus);
			toReturn.Add("InvoiceType", _invoiceType);
			toReturn.Add("PayableTo", _payableTo);
			toReturn.Add("InvoiceDocuments", _invoiceDocuments);
			toReturn.Add("InvoiceLineGroups", _invoiceLineGroups);
			toReturn.Add("InvoiceStatusChanges", _invoiceStatusChanges);
			return toReturn;
		}

		/// <summary> Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}


		#region Custom Property Hashtable Setup
		/// <summary> Initializes the hashtables for the entity type and entity field custom properties. </summary>
		private static void SetupCustomPropertyHashtables()
		{
			_customProperties = new Dictionary<string, string>();
			_fieldsCustomProperties = new Dictionary<string, Dictionary<string, string>>();
			Dictionary<string, string> fieldHashtable;
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("InvoiceId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("Identifier", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("InvoiceDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("InvoiceStatusId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("UpdateDate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("TaxRate", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("Total", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("InvoiceTypeId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("PayableToId", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("InvoicePeriodBegin", fieldHashtable);
			fieldHashtable = new Dictionary<string, string>();
			_fieldsCustomProperties.Add("InvoicePeriodEnd", fieldHashtable);
		}
		#endregion

		/// <summary> Removes the sync logic for member _invoiceStatus</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncInvoiceStatus(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _invoiceStatus, new PropertyChangedEventHandler(OnInvoiceStatusPropertyChanged), "InvoiceStatus", "Invoices", PsychologicalServices.Data.RelationClasses.StaticInvoiceRelations.InvoiceStatusEntityUsingInvoiceStatusIdStatic, true, new int[] { (int)InvoiceFieldIndex.InvoiceStatusId });
		}

		/// <summary> setups the sync logic for member _invoiceStatus</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncInvoiceStatus(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _invoiceStatus, new PropertyChangedEventHandler( OnInvoiceStatusPropertyChanged ), "InvoiceStatus", "Invoices", PsychologicalServices.Data.RelationClasses.StaticInvoiceRelations.InvoiceStatusEntityUsingInvoiceStatusIdStatic, true, new string[] {  }, new int[] { (int)InvoiceFieldIndex.InvoiceStatusId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnInvoiceStatusPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _invoiceType</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncInvoiceType(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _invoiceType, new PropertyChangedEventHandler(OnInvoiceTypePropertyChanged), "InvoiceType", "Invoices", PsychologicalServices.Data.RelationClasses.StaticInvoiceRelations.InvoiceTypeEntityUsingInvoiceTypeIdStatic, true, new int[] { (int)InvoiceFieldIndex.InvoiceTypeId });
		}

		/// <summary> setups the sync logic for member _invoiceType</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncInvoiceType(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _invoiceType, new PropertyChangedEventHandler( OnInvoiceTypePropertyChanged ), "InvoiceType", "Invoices", PsychologicalServices.Data.RelationClasses.StaticInvoiceRelations.InvoiceTypeEntityUsingInvoiceTypeIdStatic, true, new string[] {  }, new int[] { (int)InvoiceFieldIndex.InvoiceTypeId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnInvoiceTypePropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Removes the sync logic for member _payableTo</summary>
		/// <param name="signalRelatedEntity">If set to true, it will call the related entity's UnsetRelatedEntity method</param>
		/// <param name="resetFKFields">if set to true it will also reset the FK fields pointing to the related entity</param>
		private void DesetupSyncPayableTo(bool signalRelatedEntity, bool resetFKFields)
		{
			DesetupSync(signalRelatedEntity, resetFKFields, ref _payableTo, new PropertyChangedEventHandler(OnPayableToPropertyChanged), "PayableTo", "Invoices", PsychologicalServices.Data.RelationClasses.StaticInvoiceRelations.UserEntityUsingPayableToIdStatic, true, new int[] { (int)InvoiceFieldIndex.PayableToId });
		}

		/// <summary> setups the sync logic for member _payableTo</summary>
		/// <param name="relatedEntity">Instance to set as the related entity of type entityType</param>
		private void SetupSyncPayableTo(IEntityCore relatedEntity)
		{
			SetupSync(relatedEntity, ref _payableTo, new PropertyChangedEventHandler( OnPayableToPropertyChanged ), "PayableTo", "Invoices", PsychologicalServices.Data.RelationClasses.StaticInvoiceRelations.UserEntityUsingPayableToIdStatic, true, new string[] {  }, new int[] { (int)InvoiceFieldIndex.PayableToId }); 
		}
		
		/// <summary>Handles property change events of properties in a related entity.</summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void OnPayableToPropertyChanged( object sender, PropertyChangedEventArgs e )
		{
			switch( e.PropertyName )
			{
				default:
					break;
			}
		}

		/// <summary> Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this InvoiceEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();

			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();

		}

		#region Class Property Declarations
		/// <summary> The relations object holding all relations of this entity with other entity classes.</summary>
		public  static InvoiceRelations Relations
		{
			get	{ return new InvoiceRelations(); }
		}
		
		/// <summary> The custom properties for this entity type.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, string> CustomProperties
		{
			get { return _customProperties;}
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InvoiceDocument' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInvoiceDocuments
		{
			get	{ return new PrefetchPathElement2( new EntityCollection<InvoiceDocumentEntity>(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceDocumentEntityFactory))), (IEntityRelation)GetRelationsForField("InvoiceDocuments")[0], (int)PsychologicalServices.Data.EntityType.InvoiceEntity, (int)PsychologicalServices.Data.EntityType.InvoiceDocumentEntity, 0, null, null, null, null, "InvoiceDocuments", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany);	}
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InvoiceLineGroup' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInvoiceLineGroups
		{
			get	{ return new PrefetchPathElement2( new EntityCollection<InvoiceLineGroupEntity>(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceLineGroupEntityFactory))), (IEntityRelation)GetRelationsForField("InvoiceLineGroups")[0], (int)PsychologicalServices.Data.EntityType.InvoiceEntity, (int)PsychologicalServices.Data.EntityType.InvoiceLineGroupEntity, 0, null, null, null, null, "InvoiceLineGroups", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany);	}
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InvoiceStatusChange' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInvoiceStatusChanges
		{
			get	{ return new PrefetchPathElement2( new EntityCollection<InvoiceStatusChangeEntity>(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceStatusChangeEntityFactory))), (IEntityRelation)GetRelationsForField("InvoiceStatusChanges")[0], (int)PsychologicalServices.Data.EntityType.InvoiceEntity, (int)PsychologicalServices.Data.EntityType.InvoiceStatusChangeEntity, 0, null, null, null, null, "InvoiceStatusChanges", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany);	}
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InvoiceStatus' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInvoiceStatus
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceStatusEntityFactory))),	(IEntityRelation)GetRelationsForField("InvoiceStatus")[0], (int)PsychologicalServices.Data.EntityType.InvoiceEntity, (int)PsychologicalServices.Data.EntityType.InvoiceStatusEntity, 0, null, null, null, null, "InvoiceStatus", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InvoiceType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInvoiceType
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(InvoiceTypeEntityFactory))),	(IEntityRelation)GetRelationsForField("InvoiceType")[0], (int)PsychologicalServices.Data.EntityType.InvoiceEntity, (int)PsychologicalServices.Data.EntityType.InvoiceTypeEntity, 0, null, null, null, null, "InvoiceType", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}

		/// <summary> Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPayableTo
		{
			get	{ return new PrefetchPathElement2(new EntityCollection(EntityFactoryCache2.GetEntityFactory(typeof(UserEntityFactory))),	(IEntityRelation)GetRelationsForField("PayableTo")[0], (int)PsychologicalServices.Data.EntityType.InvoiceEntity, (int)PsychologicalServices.Data.EntityType.UserEntity, 0, null, null, null, null, "PayableTo", SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne); }
		}


		/// <summary> The custom properties for the type of this entity instance.</summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, string> CustomPropertiesOfType
		{
			get { return CustomProperties;}
		}

		/// <summary> The custom properties for the fields of this entity type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		public  static Dictionary<string, Dictionary<string, string>> FieldsCustomProperties
		{
			get { return _fieldsCustomProperties;}
		}

		/// <summary> The custom properties for the fields of the type of this entity instance. The returned Hashtable contains per fieldname a hashtable of name-value pairs. </summary>
		/// <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		[Browsable(false), XmlIgnore]
		protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType
		{
			get { return FieldsCustomProperties;}
		}

		/// <summary> The InvoiceId property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."InvoiceId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 InvoiceId
		{
			get { return (System.Int32)GetValue((int)InvoiceFieldIndex.InvoiceId, true); }
			set	{ SetValue((int)InvoiceFieldIndex.InvoiceId, value); }
		}

		/// <summary> The Identifier property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."Identifier"<br/>
		/// Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 20<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Identifier
		{
			get { return (System.String)GetValue((int)InvoiceFieldIndex.Identifier, true); }
			set	{ SetValue((int)InvoiceFieldIndex.Identifier, value); }
		}

		/// <summary> The InvoiceDate property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."InvoiceDate"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTimeOffset, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTimeOffset InvoiceDate
		{
			get { return (System.DateTimeOffset)GetValue((int)InvoiceFieldIndex.InvoiceDate, true); }
			set	{ SetValue((int)InvoiceFieldIndex.InvoiceDate, value); }
		}

		/// <summary> The InvoiceStatusId property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."InvoiceStatusId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 InvoiceStatusId
		{
			get { return (System.Int32)GetValue((int)InvoiceFieldIndex.InvoiceStatusId, true); }
			set	{ SetValue((int)InvoiceFieldIndex.InvoiceStatusId, value); }
		}

		/// <summary> The UpdateDate property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."UpdateDate"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTimeOffset, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTimeOffset UpdateDate
		{
			get { return (System.DateTimeOffset)GetValue((int)InvoiceFieldIndex.UpdateDate, true); }
			set	{ SetValue((int)InvoiceFieldIndex.UpdateDate, value); }
		}

		/// <summary> The TaxRate property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."TaxRate"<br/>
		/// Table field type characteristics (type, precision, scale, length): Decimal, 18, 4, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TaxRate
		{
			get { return (System.Decimal)GetValue((int)InvoiceFieldIndex.TaxRate, true); }
			set	{ SetValue((int)InvoiceFieldIndex.TaxRate, value); }
		}

		/// <summary> The Total property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."Total"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Total
		{
			get { return (System.Int32)GetValue((int)InvoiceFieldIndex.Total, true); }
			set	{ SetValue((int)InvoiceFieldIndex.Total, value); }
		}

		/// <summary> The InvoiceTypeId property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."InvoiceTypeId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 InvoiceTypeId
		{
			get { return (System.Int32)GetValue((int)InvoiceFieldIndex.InvoiceTypeId, true); }
			set	{ SetValue((int)InvoiceFieldIndex.InvoiceTypeId, value); }
		}

		/// <summary> The PayableToId property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."PayableToId"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 PayableToId
		{
			get { return (System.Int32)GetValue((int)InvoiceFieldIndex.PayableToId, true); }
			set	{ SetValue((int)InvoiceFieldIndex.PayableToId, value); }
		}

		/// <summary> The InvoicePeriodBegin property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."InvoicePeriodBegin"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTimeOffset, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTimeOffset InvoicePeriodBegin
		{
			get { return (System.DateTimeOffset)GetValue((int)InvoiceFieldIndex.InvoicePeriodBegin, true); }
			set	{ SetValue((int)InvoiceFieldIndex.InvoicePeriodBegin, value); }
		}

		/// <summary> The InvoicePeriodEnd property of the Entity Invoice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Invoices"."InvoicePeriodEnd"<br/>
		/// Table field type characteristics (type, precision, scale, length): DateTimeOffset, 0, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTimeOffset InvoicePeriodEnd
		{
			get { return (System.DateTimeOffset)GetValue((int)InvoiceFieldIndex.InvoicePeriodEnd, true); }
			set	{ SetValue((int)InvoiceFieldIndex.InvoicePeriodEnd, value); }
		}

		/// <summary> Gets the EntityCollection with the related entities of type 'InvoiceDocumentEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InvoiceDocumentEntity))]
		public virtual EntityCollection<InvoiceDocumentEntity> InvoiceDocuments
		{
			get { return GetOrCreateEntityCollection<InvoiceDocumentEntity, InvoiceDocumentEntityFactory>("Invoice", true, false, ref _invoiceDocuments);	}
		}

		/// <summary> Gets the EntityCollection with the related entities of type 'InvoiceLineGroupEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InvoiceLineGroupEntity))]
		public virtual EntityCollection<InvoiceLineGroupEntity> InvoiceLineGroups
		{
			get { return GetOrCreateEntityCollection<InvoiceLineGroupEntity, InvoiceLineGroupEntityFactory>("Invoice", true, false, ref _invoiceLineGroups);	}
		}

		/// <summary> Gets the EntityCollection with the related entities of type 'InvoiceStatusChangeEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InvoiceStatusChangeEntity))]
		public virtual EntityCollection<InvoiceStatusChangeEntity> InvoiceStatusChanges
		{
			get { return GetOrCreateEntityCollection<InvoiceStatusChangeEntity, InvoiceStatusChangeEntityFactory>("Invoice", true, false, ref _invoiceStatusChanges);	}
		}

		/// <summary> Gets / sets related entity of type 'InvoiceStatusEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual InvoiceStatusEntity InvoiceStatus
		{
			get	{ return _invoiceStatus; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncInvoiceStatus(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "Invoices", "InvoiceStatus", _invoiceStatus, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'InvoiceTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual InvoiceTypeEntity InvoiceType
		{
			get	{ return _invoiceType; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncInvoiceType(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "Invoices", "InvoiceType", _invoiceType, true); 
				}
			}
		}

		/// <summary> Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual UserEntity PayableTo
		{
			get	{ return _payableTo; }
			set
			{
				if(this.IsDeserializing)
				{
					SetupSyncPayableTo(value);
				}
				else
				{
					SetSingleRelatedEntityNavigator(value, "Invoices", "PayableTo", _payableTo, true); 
				}
			}
		}
	
		/// <summary> Gets the type of the hierarchy this entity is in. </summary>
		protected override InheritanceHierarchyType LLBLGenProIsInHierarchyOfType
		{
			get { return InheritanceHierarchyType.None;}
		}
		
		/// <summary> Gets or sets a value indicating whether this entity is a subtype</summary>
		protected override bool LLBLGenProIsSubType
		{
			get { return false;}
		}
		
		/// <summary>Returns the PsychologicalServices.Data.EntityType enum value for this entity.</summary>
		[Browsable(false), XmlIgnore]
		protected override int LLBLGenProEntityTypeValue 
		{ 
			get { return (int)PsychologicalServices.Data.EntityType.InvoiceEntity; }
		}

		#endregion


		#region Custom Entity code
		
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END
		#endregion

		#region Included code

		#endregion
	}
}
