//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using PsychologicalServices.Data;
using PsychologicalServices.Data.FactoryClasses;
using PsychologicalServices.Data.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PsychologicalServices.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AttributeType. </summary>
	public partial class AttributeTypeRelations
	{
		/// <summary>CTor</summary>
		public AttributeTypeRelations()
		{
		}

		/// <summary>Gets all relations of the AttributeTypeEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.AssessmentTypeAttributeTypeEntityUsingAttributeTypeId);
			toReturn.Add(this.AttributeEntityUsingAttributeTypeId);
			return toReturn;
		}

		#region Class Property Declarations

		/// <summary>Returns a new IEntityRelation object, between AttributeTypeEntity and AssessmentTypeAttributeTypeEntity over the 1:n relation they have, using the relation between the fields:
		/// AttributeType.AttributeTypeId - AssessmentTypeAttributeType.AttributeTypeId
		/// </summary>
		public virtual IEntityRelation AssessmentTypeAttributeTypeEntityUsingAttributeTypeId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany, "AssessmentTypeAttributeTypes" , true);
				relation.AddEntityFieldPair(AttributeTypeFields.AttributeTypeId, AssessmentTypeAttributeTypeFields.AttributeTypeId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("AttributeTypeEntity", true);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("AssessmentTypeAttributeTypeEntity", false);
				return relation;
			}
		}

		/// <summary>Returns a new IEntityRelation object, between AttributeTypeEntity and AttributeEntity over the 1:n relation they have, using the relation between the fields:
		/// AttributeType.AttributeTypeId - Attribute.AttributeTypeId
		/// </summary>
		public virtual IEntityRelation AttributeEntityUsingAttributeTypeId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany, "Attributes" , true);
				relation.AddEntityFieldPair(AttributeTypeFields.AttributeTypeId, AttributeFields.AttributeTypeId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("AttributeTypeEntity", true);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("AttributeEntity", false);
				return relation;
			}
		}


		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAttributeTypeRelations
	{
		internal static readonly IEntityRelation AssessmentTypeAttributeTypeEntityUsingAttributeTypeIdStatic = new AttributeTypeRelations().AssessmentTypeAttributeTypeEntityUsingAttributeTypeId;
		internal static readonly IEntityRelation AttributeEntityUsingAttributeTypeIdStatic = new AttributeTypeRelations().AttributeEntityUsingAttributeTypeId;

		/// <summary>CTor</summary>
		static StaticAttributeTypeRelations()
		{
		}
	}
}
