//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using PsychologicalServices.Data;
using PsychologicalServices.Data.FactoryClasses;
using PsychologicalServices.Data.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PsychologicalServices.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: GoseSocialAndLeisureRestrictionExtent. </summary>
	public partial class GoseSocialAndLeisureRestrictionExtentRelations
	{
		/// <summary>CTor</summary>
		public GoseSocialAndLeisureRestrictionExtentRelations()
		{
		}

		/// <summary>Gets all relations of the GoseSocialAndLeisureRestrictionExtentEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.GoseInterviewEntityUsingSocialAndLeisureExtentOfRestrictionId);
			return toReturn;
		}

		#region Class Property Declarations

		/// <summary>Returns a new IEntityRelation object, between GoseSocialAndLeisureRestrictionExtentEntity and GoseInterviewEntity over the 1:n relation they have, using the relation between the fields:
		/// GoseSocialAndLeisureRestrictionExtent.GoseSocialAndLeisureRestrictionExtentId - GoseInterview.SocialAndLeisureExtentOfRestrictionId
		/// </summary>
		public virtual IEntityRelation GoseInterviewEntityUsingSocialAndLeisureExtentOfRestrictionId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany, "GoseInterviews" , true);
				relation.AddEntityFieldPair(GoseSocialAndLeisureRestrictionExtentFields.GoseSocialAndLeisureRestrictionExtentId, GoseInterviewFields.SocialAndLeisureExtentOfRestrictionId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("GoseSocialAndLeisureRestrictionExtentEntity", true);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("GoseInterviewEntity", false);
				return relation;
			}
		}


		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticGoseSocialAndLeisureRestrictionExtentRelations
	{
		internal static readonly IEntityRelation GoseInterviewEntityUsingSocialAndLeisureExtentOfRestrictionIdStatic = new GoseSocialAndLeisureRestrictionExtentRelations().GoseInterviewEntityUsingSocialAndLeisureExtentOfRestrictionId;

		/// <summary>CTor</summary>
		static StaticGoseSocialAndLeisureRestrictionExtentRelations()
		{
		}
	}
}
