CREATE TABLE [dbo].[AppointmentProtocolResponses] (
    [AppointmentId]                                 INT                NOT NULL,
    [OnTimeArrivalAndNotificationId]                INT                NULL,
    [ClaimantArrivalNotificationId]                 INT                NULL,
    [CovidFormsCompletedBeforeEnteringRoomId]       INT                NULL,
    [TestedClaimantsEnglishReadingLevelId]          INT                NULL,
    [TommSimsScoreNotificationId]                   INT                NULL,
    [AskedWhichTestsShouldBeRemovedId]              INT                NULL,
    [AdvisedOfUnexpectedDelaysId]                   INT                NULL,
    [AfterAssessmentNotificationId]                 INT                NULL,
    [AllPapersHaveClaimantInitialsAndDateId]        INT                NULL,
    [ScoringDoubleCheckedId]                        INT                NULL,
    [RelevantObservationsDocumentedId]              INT                NULL,
    [ErrorCheckedObservationsId]                    INT                NULL,
    [AllFormsCompletedId]                           INT                NULL,
    [TimeAssessmentLabelCompletedId]                INT                NULL,
    [ScansUploadedNotificationId]                   INT                NULL,
    [UploadedScanLegibilityVerifiedId]              INT                NULL,
    [SpareSetReplenishmentRequestSentId]            INT                NULL,
    [RespondedToQuestionsWithinRequiredTimeframeId] INT                NULL,
    [StapledItemsTogetherId]                        INT                NULL,
    [WillPersonallyDropOffPackageId]                INT                NULL,
    [Comments]                                      VARCHAR (1000)     NULL,
    [CreateDate]                                    DATETIMEOFFSET (7) CONSTRAINT [DF_AppointmentProtocolResponses_CreatedDate] DEFAULT (sysutcdatetime()) NOT NULL,
    [CreateUserId]                                  INT                NOT NULL,
    [UpdateDate]                                    DATETIMEOFFSET (7) CONSTRAINT [DF_AppointmentProtocolResponses_UpdateDate] DEFAULT (sysutcdatetime()) NOT NULL,
    [UpdateUserId]                                  INT                NOT NULL,
    CONSTRAINT [PK_AppointmentProtocolResponses_1] PRIMARY KEY CLUSTERED ([AppointmentId] ASC),
    CONSTRAINT [FK_AppointmentProtocolResponses_AdvisedOfUnexpectedDelays] FOREIGN KEY ([AdvisedOfUnexpectedDelaysId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_AfterAssessmentNotification] FOREIGN KEY ([AfterAssessmentNotificationId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_AllFormsCompleted] FOREIGN KEY ([AllFormsCompletedId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_AllPapersHaveClaimantInitialsAndDate] FOREIGN KEY ([AllPapersHaveClaimantInitialsAndDateId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_Appointments] FOREIGN KEY ([AppointmentId]) REFERENCES [dbo].[Appointments] ([AppointmentId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_AskedWhichTestsShouldBeRemoved] FOREIGN KEY ([AskedWhichTestsShouldBeRemovedId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_ClaimantArrivalNotification] FOREIGN KEY ([ClaimantArrivalNotificationId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_CovidFormsCompletedBeforeEnteringRoom] FOREIGN KEY ([CovidFormsCompletedBeforeEnteringRoomId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_CreateUser] FOREIGN KEY ([CreateUserId]) REFERENCES [dbo].[Users] ([UserId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_ErrorCheckedObservations] FOREIGN KEY ([ErrorCheckedObservationsId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_OnTimeArrivalAndNotification] FOREIGN KEY ([OnTimeArrivalAndNotificationId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_RelevantObservationsDocumented] FOREIGN KEY ([RelevantObservationsDocumentedId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_RespondedToQuestionsWithinRequiredTimeframe] FOREIGN KEY ([RespondedToQuestionsWithinRequiredTimeframeId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_ScansUploadedNotification] FOREIGN KEY ([ScansUploadedNotificationId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_ScoringDoubleChecked] FOREIGN KEY ([ScoringDoubleCheckedId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_SpareSetReplenishmentRequestSent] FOREIGN KEY ([SpareSetReplenishmentRequestSentId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_StapledItemsTogether] FOREIGN KEY ([StapledItemsTogetherId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_TestedClaimantsEnglishReadingLevel] FOREIGN KEY ([TestedClaimantsEnglishReadingLevelId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_TimeAssessmentLabelCompleted] FOREIGN KEY ([TimeAssessmentLabelCompletedId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_TommSimsScoreNotification] FOREIGN KEY ([TommSimsScoreNotificationId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_UpdateUser] FOREIGN KEY ([UpdateUserId]) REFERENCES [dbo].[Users] ([UserId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_UploadedScanLegibilityVerified] FOREIGN KEY ([UploadedScanLegibilityVerifiedId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId]),
    CONSTRAINT [FK_AppointmentProtocolResponses_WillPersonallyDropOffPackage] FOREIGN KEY ([WillPersonallyDropOffPackageId]) REFERENCES [dbo].[AppointmentProtocolResponseValues] ([AppointmentProtocolResponseValueId])
);

